'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, ArrowRight, ChevronDown, Heart, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'

export const catalog = [
  { name: 'The Linen Blazer', price: 6499, image: '/images/linen-fashion.png', tag: 'Bestseller', category: 'Tailoring', color: 'Natural' },
  { name: 'The Column Dress', price: 4999, image: '/images/editorial-fashion.png', tag: 'New in', category: 'Dresses', color: 'Black' },
  { name: 'The Everyday Shirt', price: 3499, image: '/images/soft-tailoring.png', tag: 'Essential', category: 'Shirts', color: 'Ivory' },
  { name: 'The Pleat Trouser', price: 4299, image: '/images/lookbook-fashion.png', tag: 'New in', category: 'Tailoring', color: 'Charcoal' },
  { name: 'The Studio Top', price: 2899, image: '/images/studio-look.png', tag: 'Essential', category: 'Tops', color: 'Ecru' },
  { name: 'The Terrace Skirt', price: 3899, image: '/images/terrace-look.png', tag: 'Limited', category: 'Bottoms', color: 'Sand' },
]
const money = (n: number) => `₹${n.toLocaleString('en-IN')}`

export function StoreHeader() { return <><div className="announcement">Complimentary shipping on orders over ₹3,000 <span>·</span> Chennai, India</div><header className="site-header"><nav className="desktop-nav"><Link href="/collection">Shop</Link><Link href="/#story">Our story</Link><Link href="/#journal">Journal</Link></nav><Link href="/" className="wordmark">[ AURORA ]</Link><div className="header-actions"><Link className="icon-button" href="/wishlist" aria-label="Wishlist"><Heart /></Link><Link className="icon-button" href="/cart" aria-label="Shopping bag"><ShoppingBag /><sup>2</sup></Link></div></header></> }
export function ProductCard({ product }: { product: typeof catalog[number] }) { const [liked, setLiked] = useState(false); return <article className="product-card"><div className="product-image"><Link href="/product/the-linen-blazer"><Image src={product.image} alt={product.name} fill sizes="(max-width: 768px) 50vw, 25vw" /></Link><span className="product-tag">{product.tag}</span><button className="wishlist-button" onClick={() => setLiked(!liked)} aria-label={`Save ${product.name}`}><Heart fill={liked ? 'currentColor' : 'none'} /></button></div><div className="product-meta"><div><h3>{product.name}</h3><p>Chennai studio / 01</p></div><strong>{money(product.price)}</strong></div></article> }

export function CollectionPage() { const [category, setCategory] = useState('All pieces'); const filtered = category === 'All pieces' ? catalog : catalog.filter(p => p.category === category); return <main><StoreHeader /><section className="page-intro"><span className="eyebrow">01 / The collection</span><h1>Pieces for<br /><em>every day.</em></h1><p>A considered wardrobe of intelligent silhouettes, natural textures and easy confidence.</p></section><section className="collection-toolbar"><div className="collection-filters">{['All pieces','Tailoring','Dresses','Shirts','Tops'].map(item => <button key={item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div><button className="filter-link">Sort by / Featured <ChevronDown /></button></section><section className="collection-grid">{filtered.map(product => <ProductCard key={product.name} product={product} />)}</section></main> }

export function ProductPage() { const [size, setSize] = useState('S'); const [added, setAdded] = useState(false); return <main><StoreHeader /><div className="product-detail"><div className="product-gallery"><Image src="/images/linen-fashion.png" alt="The Linen Blazer front view" fill priority sizes="(max-width: 768px) 100vw, 55vw" /><div className="gallery-label">01 / 03</div></div><div className="product-buy"><Link href="/collection" className="back-link"><ArrowLeft /> Back to collection</Link><span className="eyebrow">Aurora / Tailoring</span><h1>The Linen<br /><em>Blazer.</em></h1><div className="detail-price">₹6,499</div><p className="detail-copy">A relaxed, softly structured blazer in breathable linen. Cut for an easy fit with considered proportions.</p><div className="detail-rule" /><div className="option-row"><span>Colour</span><b>Natural</b></div><div className="option-row"><span>Size</span><Link href="#size">Size guide</Link></div><div className="size-options">{['XS','S','M','L','XL'].map(s => <button key={s} className={size === s ? 'selected' : ''} onClick={() => setSize(s)}>{s}</button>)}</div><button className="add-button" onClick={() => setAdded(true)}>{added ? 'Added to bag' : 'Add to bag'} <ArrowRight /></button><div className="detail-notes"><span>Free shipping over ₹3,000</span><span>14-day easy returns</span><span>Made in Chennai</span></div></div></div></main> }

export function CartPage() { const [qty, setQty] = useState(1); const subtotal = 6499 * qty; return <main><StoreHeader /><div className="simple-page-head"><span className="eyebrow">Your selection</span><h1>Your <em>bag.</em></h1></div><div className="cart-layout"><section className="cart-items"><div className="cart-item"><div className="cart-thumb"><Image src="/images/linen-fashion.png" alt="The Linen Blazer" fill sizes="130px" /></div><div className="cart-item-info"><span className="eyebrow">Tailoring / Natural</span><h2>The Linen Blazer</h2><p>Size: S</p><div className="quantity"><button onClick={() => setQty(Math.max(1, qty - 1))} aria-label="Decrease quantity"><Minus /></button><span>{qty}</span><button onClick={() => setQty(qty + 1)} aria-label="Increase quantity"><Plus /></button></div></div><strong>{money(subtotal)}</strong><button className="remove" aria-label="Remove item"><Trash2 /></button></div><div className="upsell"><span className="eyebrow">Complete the look</span><h2>The Everyday Shirt</h2><Link href="/product/the-linen-blazer" className="text-link">Add to bag <ArrowRight /></Link></div></section><aside className="order-summary"><span className="eyebrow">Order summary</span><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Shipping</span><b>Complimentary</b></div><div className="summary-total"><span>Total</span><b>{money(subtotal)}</b></div><Link href="/checkout" className="add-button">Proceed to checkout <ArrowRight /></Link><p>Taxes included. Secure checkout.</p></aside></div></main> }

export function CheckoutPage() { const [step, setStep] = useState(1); return <main><StoreHeader /><div className="checkout"><div className="checkout-main"><div className="checkout-steps">{['Information','Delivery','Payment'].map((name, i) => <button key={name} className={step === i + 1 ? 'active' : ''} onClick={() => setStep(i + 1)}><span>0{i + 1}</span>{name}</button>)}</div>{step === 1 && <div className="checkout-form"><span className="eyebrow">Step 01 / Information</span><h1>Where should we<br /><em>send your order?</em></h1><label>Email address<input type="email" placeholder="you@example.com" /></label><label>Full name<input placeholder="Your full name" /></label><label>Address<input placeholder="House number and street" /></label><div className="form-row"><label>City<input placeholder="Chennai" /></label><label>PIN code<input placeholder="600001" /></label></div><button className="add-button" onClick={() => setStep(2)}>Continue to delivery <ArrowRight /></button></div>}{step === 2 && <div className="checkout-form"><span className="eyebrow">Step 02 / Delivery</span><h1>Choose your<br /><em>delivery.</em></h1><button className="delivery-choice active"><span><b>Standard delivery</b><small>3–5 business days</small></span><strong>Free</strong></button><button className="add-button" onClick={() => setStep(3)}>Continue to payment <ArrowRight /></button></div>}{step === 3 && <div className="checkout-form"><span className="eyebrow">Step 03 / Payment</span><h1>Almost<br /><em>there.</em></h1><label>Card number<input placeholder="1234  5678  9012  3456" /></label><div className="form-row"><label>Expiry<input placeholder="MM / YY" /></label><label>CVV<input placeholder="123" /></label></div><button className="add-button">Place order <ArrowRight /></button></div>}</div><aside className="checkout-summary"><span className="eyebrow">Your order</span><div className="summary-product"><Image src="/images/linen-fashion.png" alt="The Linen Blazer" width={80} height={100} /><span>The Linen Blazer<small>Natural / S</small></span><b>₹6,499</b></div><div className="summary-total"><span>Total</span><b>₹6,499</b></div></aside></div></main> }

export function WishlistPage() { return <main><StoreHeader /><div className="simple-page-head"><span className="eyebrow">Saved for later</span><h1>Your <em>wishlist.</em></h1></div><section className="collection-grid wishlist-grid">{catalog.slice(0, 4).map(product => <ProductCard key={product.name} product={product} />)}</section></main> }
                    
               
